#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import ctypes
from ctypes import *

'''----------------结构体定义--------------------------------------'''
#LKIF_FLOATRESULT 枚举类
(LKIF_FLOATRESULT_VALID,LKIF_FLOATRESULT_RANGEOVER_P,
	LKIF_FLOATRESULT_RANGEOVER_N,LKIF_FLOATRESULT_WAITING)=(0,1,2,3)


#LKIF_FLOATVALUE 结构体
class LKIF_FLOATVALUE(Structure):
	_fields_=[("LKIF_FLOATRESULT",c_int),("Value",c_float)]

#LKIF_FIGUREDATA 结构体
class LKIF_FIGUREDATA(object):
	"""docstring for LKIF_FIGUREDATA"""
	_fields_=[("ToleUpper",LKIF_FLOATVALUE),("ToleLower",LKIF_FLOATVALUE),("ToleLower",LKIF_FLOATVALUE)
	,("ToleLower",LKIF_FLOATVALUE),("ToleLower",LKIF_FLOATVALUE),("ToleLower",LKIF_FLOATVALUE),("ToleLower",LKIF_FLOATVALUE),
	("DataCnt",c_long),("HighDataCnt",c_long),("GoDataCnt",c_long),("LowDataCnt",c_long)]

#LKIF_ABLEMODE 枚举类
(LKIF_ABLEMODE_AUTO,LKIF_ABLEMODE_MANUAL)=(0,1)

#LKIF_MEASUREMODE 枚举类
(LKIF_MEASUREMODE_NORMAL,LKIF_MEASUREMODE_HALF_T,LKIF_MEASUREMDOE_TRAN_1,LKIF_MEASUREMODE_TRAN_2,LKIF_MEASUREMODE_MRS)=(0,1,2,3,4)

#LKIF_REFLECTIONMODE 枚举类
(LKIF_REFLECTIONMODE_DIFFUSION,LKIF_REFLECTIONMODE_MIRROR)=(0,1)

#LKIF_CALCMETHOD 枚举类
(LKIF_CALCMETHOD_HEADA,LKIF_CALCMETHOD_HEADB,LKIF_CALCMETHOD_HEAD_HEADA_PLUS_HEADB,
	LKIF_CALCMETHOD_HEAD_HEADA_MINUS_HEADB,LKIF_CALCMETHOD_HEAD_HEADA_TRANSPARENT,
	LKIF_CALCMETHOD_HEAD_HEADB_TRANSPARENT)=(0,1,2,3,4,5)

#LKIF_FILTERMODE 枚举类
(LKIF_FILTERMODE_MOVING_AVERAGE,LKIF_FILTERMODE_LOWPASS,LKIF_FILTERMODE_HIGHPASS)=(0,1,2)

#LKIF_AVERAGE 枚举类
(LKIF_AVERAGE_1,LKIF_AVERAGE_4,LKIF_AVERAGE_16,LKIF_AVERAGE_64,LKIF_AVERAGE_256,LKIF_AVERAGE_1024,
	LKIF_AVERAGE_4096,LKIF_AVERAGE_16384,LKIF_AVERAGE_65536,LKIF_AVERAGE_262144)=(0,1,2,3,4,5,6,7,8,9)

#LKIF_CUTOFFFREQUENCY 枚举类
(LKIF_CUTOFFFREQUENCY_1000,LKIF_CUTOFFFREQUENCY_300,LKIF_CUTOFFFREQUENCY_100,LKIF_CUTOFFFREQUENCY_30,
	LKIF_CUTOFFFREQUENCY_10,LKIF_CUTOFFFREQUENCY_3,LKIF_CUTOFFFREQUENCY_1,LKIF_CUTOFFFREQUENCY_0_3,LKIF_CUTOFFFREQUENCY_0_1)=(0,1,2,3,4,5,6,7,8)

#LKIF_TRIGGERMODE 枚举类
(LKIF_TRIGGERMODE_EXT1,LKIF_TRIGGERMODE_EXT2)=(0,1)

#LKIF_CALCMODE 枚举类
(LKIF_CALCMODE_NORMAL,LKIF_CALCMODE_PEAKHOLD,LKIF_CALCMODE_BOTTOMHOLD,
	LKIF_CALCMODE_PEAKTOPEAKHOLD,LKIF_CALCMODE_SAMPLEHOLD,LKIF_CALCMODE_AVERAGEHOLD)=(0,1,2,3,4,5)

#LKIF_DISPLAYUNIT 枚举类
(LKIF_DISPLAYUNIT_0000_01MM,LKIF_DISPLAYUNIT_000_001MM,LKIF_DISPLAYUNIT_00_0001MM,LKIF_DISPLAYUNIT_0_00001MM,
	LKIF_DISPLAYUNIT_00000_1UM,LKIF_DISPLAYUNIT_0000_01UM)=(0,1,2,3,4,5)

#LKIF_TARGETOUT 枚举类
(LKIF_TARGETOUT_NONE,LKIF_TARGETOUT_OUT1,LKIF_TARGETOUT_OUT2,LKIF_TARGETOUT_BOTH)=(0,1,2,3)

#LKIF_STORAGECYCLE 枚举类
(LKIF_STORAGECYCLE_1,LKIF_STORAGECYCLE_2,LKIF_STORAGECYCLE_5,LKIF_STORAGECYCLE_10,LKIF_STORAGECYCLE_20,
	LKIF_STORAGECYCLE_50,LKIF_STORAGECYCLE_100,LKIF_STORAGECYCLE_200,LKIF_STORAGECYCLE_500,LKIF_STORAGECYCLE_1000)=(0,1,2,3,4,5,6,7,8,9)

#LKIF_SAMPLINGCYCLE 枚举类
(LKIF_SAMPLINGCYCLE_20USEC,LKIF_SAMPLINGCYCLE_50USEC,LKIF_SAMPLINGCYCLE_100USEC,
	LKIF_SAMPLINGCYCLE_200USEC,LKIF_SAMPLINGCYCLE_500USEC,LKIF_SAMPLINGCYCLE_1MSEC)=(0,1,2,3,4,5)

#LKIF_SYNCHRONIZATION 枚举类
(LKIF_SYNCHRONIZATION_ASYNCHRONOUS,LKIF_SYNCHRONIZATION_SYNCHRONIZED)=(0,1)

#LKIF_TOLERANCE_COMPARATOR_OUTPUT_FORMAT 枚举类
(LKIF_TOLERANCE_COMPARATOR_OUTPUT_FORMAT_NORMAL,
	LKIF_TOLERANCE_COMPARATOR_OUTPUT_FORMAT_HOLD,LKIF_TOLERANCE_COMPARATOR_OUTPUT_FORMAT_OFF_DELAY)=(0,1,2)

#LKIF_STOROBETIME 枚举类
(LKIF_STOROBETIME_2MS,LKIF_STOROBETIME_5MS,LKIF_STOROBETIME_10MS,LKIF_STOROBETIME_20MS)=(0,1,2,3)

#LKIF_MODE 枚举类
(LKIF_MODE_NORMAL,LKIF_MODE_COMMUNICATION)=(0,1)